
<!-- chama o header primeiro -->
<?php require VIEWS_PATH . 'includes/header.phtml';?>

<!--Chama a main principal chamada "home" -->
<div class="container">

<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1>Gerenciador de Gastos Pessoais!</h1>
  <p>
    Projeto 3 - Painel de Gastos Pessoais.
  </p>
  <p>
    <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais &raquo;</a>
  </p>
</div>

<div class="col-md-12">

  
</div>

</div> <!-- /container -->

<!-- chama o footer -->
<?php require VIEWS_PATH . 'includes/footer.phtml';?>